export const NEW_RESERVATION = "NEW RESERVATION";
export const FETCHED = 'FETCH RESERVATIONS';
export const CURRENT_EMPLOYEE = "CURRENT EMPLOYEE";
export const ADMIN = "ADMIN";
export const FETCHING = "FETCHING";